version: "3"

services:
  mongo:
    container_name: mongo_candidates_db
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
    command: mongod --quiet --logpath /dev/null

  candidates-api:
    container_name: candidates_api
    build:
      context: ./candidates-api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    links:
      - mongo
    volumes:
      - ./candidates-api:/usr/src/app
    depends_on:
      - mongo

  candidates-web:
    container_name: candidates_web
    build:
      context: ./candidates-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - candidates-api
